apiVersion: 1

notifiers:
  # Slack notification channel
  - name: cultural-sound-lab-slack
    type: slack
    uid: cultural-sound-lab-slack
    org_id: 1
    is_default: true
    send_reminder: true
    disable_resolve_message: false
    frequency: "10s"
    settings:
      url: ${SLACK_WEBHOOK_URL}
      channel: "#alerts"
      username: "Cultural Sound Lab Alerts"
      title: |
        {{ range .Alerts }}
        {{ if eq .Status "firing" }}🔥 FIRING {{ else }}✅ RESOLVED {{ end }}
        {{ .Annotations.summary }}
        {{ end }}
      text: |
        {{ range .Alerts }}
        **Alert:** {{ .Annotations.summary }}
        **Description:** {{ .Annotations.description }}
        **Severity:** {{ .Labels.severity }}
        **Service:** {{ .Labels.service }}
        **Team:** {{ .Labels.team }}
        {{ if .Annotations.runbook_url }}**Runbook:** {{ .Annotations.runbook_url }}{{ end }}
        **Status:** {{ .Status }}
        **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
        {{ if ne .Status "firing" }}**Resolved:** {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
        ---
        {{ end }}

  # Email notification channel
  - name: cultural-sound-lab-email
    type: email
    uid: cultural-sound-lab-email
    org_id: 1
    is_default: false
    send_reminder: true
    disable_resolve_message: false
    frequency: "10s"
    settings:
      addresses: ${ALERT_EMAIL}
      subject: |
        Cultural Sound Lab Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      body: |
        <h2>Cultural Sound Lab Alert</h2>
        {{ range .Alerts }}
        <h3>{{ if eq .Status "firing" }}🔥 FIRING{{ else }}✅ RESOLVED{{ end }} {{ .Annotations.summary }}</h3>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Service:</strong> {{ .Labels.service }}</p>
        <p><strong>Team:</strong> {{ .Labels.team }}</p>
        {{ if .Annotations.runbook_url }}<p><strong>Runbook:</strong> <a href="{{ .Annotations.runbook_url }}">{{ .Annotations.runbook_url }}</a></p>{{ end }}
        <p><strong>Status:</strong> {{ .Status }}</p>
        <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
        {{ if ne .Status "firing" }}<p><strong>Resolved:</strong> {{ .EndsAt.Format "2006-01-02 15:04:05" }}</p>{{ end }}
        <hr>
        {{ end }}

  # PagerDuty notification channel
  - name: cultural-sound-lab-pagerduty
    type: pagerduty
    uid: cultural-sound-lab-pagerduty
    org_id: 1
    is_default: false
    send_reminder: true
    disable_resolve_message: false
    frequency: "10s"
    settings:
      integrationKey: ${PAGERDUTY_INTEGRATION_KEY}
      severity: |
        {{ range .Alerts }}
        {{ if eq .Labels.severity "critical" }}critical
        {{ else if eq .Labels.severity "warning" }}warning
        {{ else }}info{{ end }}
        {{ end }}
      client: "Cultural Sound Lab Grafana"
      clientUrl: "${GRAFANA_URL}"
      description: |
        {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      details: |
        {
          {{ range $index, $alert := .Alerts }}
          {{ if $index }},{{ end }}
          "alert_{{ $index }}": {
            "summary": "{{ $alert.Annotations.summary }}",
            "description": "{{ $alert.Annotations.description }}",
            "severity": "{{ $alert.Labels.severity }}",
            "service": "{{ $alert.Labels.service }}",
            "team": "{{ $alert.Labels.team }}",
            "status": "{{ $alert.Status }}",
            "started": "{{ $alert.StartsAt.Format "2006-01-02T15:04:05Z07:00" }}"
            {{ if ne $alert.Status "firing" }},"resolved": "{{ $alert.EndsAt.Format "2006-01-02T15:04:05Z07:00" }}"{{ end }}
          }
          {{ end }}
        }

  # Microsoft Teams notification channel
  - name: cultural-sound-lab-teams
    type: teams
    uid: cultural-sound-lab-teams
    org_id: 1
    is_default: false
    send_reminder: true
    disable_resolve_message: false
    frequency: "10s"
    settings:
      url: ${TEAMS_WEBHOOK_URL}
      title: |
        Cultural Sound Lab Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      sectionTitle: |
        {{ range .Alerts }}
        {{ if eq .Status "firing" }}🔥 FIRING{{ else }}✅ RESOLVED{{ end }}
        {{ end }}
      text: |
        {{ range .Alerts }}
        **Alert:** {{ .Annotations.summary }}
        
        **Description:** {{ .Annotations.description }}
        
        **Severity:** {{ .Labels.severity }}
        
        **Service:** {{ .Labels.service }}
        
        **Team:** {{ .Labels.team }}
        
        {{ if .Annotations.runbook_url }}**Runbook:** [View Runbook]({{ .Annotations.runbook_url }}){{ end }}
        
        **Status:** {{ .Status }}
        
        **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
        
        {{ if ne .Status "firing" }}**Resolved:** {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
        
        ---
        {{ end }}