global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Cultural Sound Lab API
  - job_name: 'cultural-sound-lab-api'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Cultural Sound Lab API Health Check
  - job_name: 'cultural-sound-lab-api-health'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 5s

  # Cultural Sound Lab Web Application
  - job_name: 'cultural-sound-lab-web'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Node Exporter (if running)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']